version: '3'
services:
  example:
    image: hashicorp/terraform:light
    working_dir: /terraform
    environment:
      AWS_SHARED_CREDENTIALS_FILE: /root/.aws/credentials
    volumes:
      - ./stacks/example:/terraform
      - ./modules:/terraform/modules
      - ~/.aws/credentials:/root/.aws/credentials:ro
